@startuml
!include ./C4_Container.puml

LAYOUT_LEFT_RIGHT()

LAYOUT_WITH_LEGEND()

AddElementTag("lowerLevelLink", $borderColor="8324db",$borderThickness="8")
AddElementTag("higherLevelLink", $borderColor="0fefe9ff",$borderThickness="8")

Container(back, "Back To Context", $link="./ContextDiagram.puml", $tags="higherLevelLink")

System(ingestion, "Ingest Platform",$link="./IngestPlatformContainer.puml", $tags="lowerLevelLink")
System(ampi, "Anonymized Master Person Index",$link="./AMPIContainer.puml", $tags="lowerLevelLink")
System(website, "tesselate.io",$link="./TesselateIOContainer.puml", $tags="lowerLevelLink")
System_Ext(research_db, "External Research Data Sink")

Container_Boundary(datamarket, "Data Market - Systems highlighted in purple are clickable links", "The boundary of the system"){
    ContainerDb(dicom, "Dicom Document Store", "Stores Dicom Documents")
    ContainerDb(cda, "CDA Document Store", "Stores CDA Documents")
    Container(search, "Search REST API", "Searches for documents and images")
    Container(proxy, "router", "Proxies requests to the correct service")
    Container(gateway, API Gateway, "API Gateway")
    ContainerDb(elk, "ELK Stack", "Stores logs")
    Container(slack, "Slack", "Chat Ops")
}

Rel(gateway, search, "Uses")
Rel(search, ampi, "Uses")
Rel(search, dicom, "Uses")
Rel(search, cda, "Uses")
Rel(ingestion, proxy, "Sends Data to")
Rel(proxy, dicom, "Writes Data to")
Rel(proxy, cda, "Writes Data to")
Rel(proxy, research_db, "Sends Data to")
Rel(website, gateway, "Uses")
Rel(gateway, proxy, "Uses")
Rel(proxy, elk, "Logs to")
Rel(search, elk, "Logs to")
Rel(slack, elk, "uses")
Rel(website, elk, "Uses")



@enduml