@startuml
!include ./C4_Container.puml

LAYOUT_WITH_LEGEND()

AddElementTag("lowerLevelLink", $borderColor="8324db",$borderThickness="8")
AddElementTag("higherLevelLink", $borderColor="0fefe9ff",$borderThickness="8")

Container(back, "Back To Context", $link="./ContextDiagram.puml", $tags="higherLevelLink")
System_Ext(hie, "Hospital HIE", "Health Information Exchange")
System_Ext(pacs, "PACS", "Picture Archiving and Communication System")
System_Ext(fhir, "FHIR Server", "Fast Healthcare Interoperability Resources Server")
System_Ext(files, "Files, FTP, DB")
System(datamarket, "Data Market",$link="./DataMarketContainer.puml", $tags="lowerLevelLink")
System(ampi, "Anonymized Master Person Index",$link="./AMPIContainer.puml", $tags="lowerLevelLink")
System(security, "Authorization Token Issuer/ Validator", "Software System")

Container_Boundary(ingest, "Ingest Platform - Systems highlighted in purple are clickable links", "The boundary of the system"){
Container(integrationEngine, "Integration Engine","Container: integration components", "Engine that integrates data from different sources")

Boundary(queue,"Document Queues"){
    ContainerQueue(image, "Medical Image Queue", File Store,"Queue for images")
    ContainerQueue(cda, "CDA Queue", "File Store","Queue for CDA documents")
    ContainerQueue(hl7, "Hl7 Queue", "File Store","Queue for Hl7 messages")
}

Boundary(etl, "ETL Processors"){
    Container(hl7processor, "Hl7 ETL Processor","Container: HL7 ETL Component", "Processes Hl7 messages")
    Container(dicom, "DICOM ETL Processor", "Container: DICOM ETL Components","Processes DICOM images")
    Container(cdaProcessor, "CDA ETL Processor", "Container: CDA ETL Components","Processes CDA documents")
    }
}
Container(hl7processor, "Hl7 ETL Processor","Container: HL7 ETL Component", "Processes Hl7 messages")
Container(dicom, "DICOM ETL Processor", "Container: DICOM ETL Components","Processes DICOM images")
Container(cdaProcessor, "CDA ETL Processor", "Container: CDA ETL Components","Processes CDA documents")
}
Lay_U(files,back)
Rel(hie, integrationEngine, "Sends Hl7 data to")
Rel(integrationEngine, hl7, "Sends Hl7 data to")
Rel(files, integrationEngine, "Sends data to")
Rel(fhir, integrationEngine, "Sends data to")
Rel_U(hl7processor, hl7, "Reads Hl7 data from")
Rel(hl7processor, ampi, "Sends Hl7 data to")
BiRel_U(integrationEngine, pacs, "Query/retrieve Image data")
Rel(integrationEngine, image, "Sends data to")
Rel_U(dicom, image, "Reads data from")
Rel(dicom, ampi, "Uses")
Rel(dicom, datamarket, "Sends data to")
Rel(integrationEngine, cda, "Sends data to")
Rel_U(cdaProcessor,cda, "Sends data to")
Rel(cdaProcessor, datamarket, "Sends data to")
Rel(cdaProcessor, ampi, "Uses")
Rel_U(ingest, security, "Uses")

@enduml